### ISSUE TITLE
Failed to call service media_player/play_media.

### ISSUE THREAD

**Issue by gbdavidx** [dnguyen800/Spotify-Playlist-Card#1]
Hi,

I tried to implement your lovelace card, i love the look of it, but having some issues

```
  - type: "custom:spotify-playlist"
    entity: sensor.playlists
    media_player: media_player.spotify
    columns: 3
    size: '140px'       
    show_name: false      
    show_title: false
    title: 'My Playlists'   
```

when i use this i get an error saying it can't find, if i change spotify-playlist to spotify-playlist-card it will show the cards (https://github.com/dnguyen800/Spotify-Playlist-Card/blob/master/spotify-playlist-card.js from the bottom javscript), but it wont play anything when i click on card

**Comment by gbdavidx** [comment]
Failed to call service media_player/play_media.
when i click on the playlist

**Comment by dnguyen800** [comment]
I'll revisit this issue soon as I plan to make some changes to make this card compatible with the Spotcast custom component.

**Comment by dnguyen800** [comment]
You found a mistake in the README documentation--thanks for pointing that out.

If you can provide some more information about your setup--what speaker are you using to play the Spotify music? I only have Chromecast speakers and thus only tested this card and Spotcast together. If you are using `media_player.spotify` as the `speaker_name`, there is a limitation with Spotify that prevents playback of music on an idle device. The workaround is to play Spotify on a device, then try pressing a button on this card. If that doesn't work, let me know.
